In [6]:
import requests
from bs4 import BeautifulSoup
url="https://altibbi.com/%D8%A7%D8%B3%D8%A6%D9%84%D8%A9-%D8%B7%D8%A8%D9%8A%D8%A9/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A"
response=requests.get(url)
soup=BeautifulSoup(response.text,"html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="ar-EG">
 <head>
  <title>
   أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي
  </title>
  <script type="application/ld+json">
   {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": "https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A#webpage",
    "url": "https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A",
    "name": "أسئلة وأجوبة طبية - أمراض الجهاز التنفسي",
    "description": "أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي",
    "inLanguage": "ar-EG"
}
  </script>
  <script>
   const IS_MOBILE = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
  </script>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=5.0" name="viewport"/>
  <meta content="Altibbi.com" name="author"/>
  <!-- Chrome, Firefox OS and Opera -->
  <meta content="#102A56" name="theme-color"/>
  <!-- Windows Phone -->
  <meta content="#195895" name="msapplication-navbutton-color"/>
  <!-- iOS Safari -->
  <meta content="#102A56" name="apple-mobile-web-app-status-bar-style"/>
  <meta content="yes" name="apple-mobile-web-app-capable">
   <meta content="yes" name="mobile-web-app-capable"/>
   <meta content="146667996661" property="fb:pages">
    <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" name="description"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="253132216348515" property="fb:app_id">
     <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي" property="og:title">
      <meta content="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" property="og:url">
       <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="og:image:secure_url">
        <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="og:image">
         <meta content="1200" property="og:image:width">
          <meta content="630" property="og:image:height">
           <meta content="الطبي" property="og:site_name"/>
           <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" property="og:description"/>
           <meta content="website" property="og:type"/>
           <meta content="موقع الطبي للمعلومات الصحية والاستشارات الطبية | أمراض، أدوية وعلاج" property="og:image:alt"/>
           <meta content="summary" property="twitter:card"/>
           <meta content="@Altibbi" property="twitter:site"/>
           <meta content="@Altibbi" property="twitter:creator"/>
           <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي" property="twitter:title"/>
           <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" property="twitter:description"/>
           <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="twitter:image"/>
           <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي" property="twitter:image:alt"/>
           <meta content="_csrf-frontend" name="csrf-param"/>
           <meta content="Vxj69pCjyXmSE60FFbR_virQN4ez5xaMiQoHebxUofM9dY6T3o6GQd0m3FxN5kjcZIZf5IOQJrT4Qn8D-QKXqg==" name="csrf-token"/>
           <link href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="canonical"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="self"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="first"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A?page=886" rel="last"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A?page=2" rel="next"/>
           <link href="/assets/f00a8642a147463b76963466ee1e53d3.css?v=1792412658" rel="stylesheet"/>
           <style>
            .free-question-banner-badge {
top: 0;
left: 0;
border-radius: 4px 0 8px 0;
}
           </style>
           <style>
            #contentNavigatorModal .modal-content{
    background-color: transparent;
    border: unset;
}

#contentNavigatorModal .modal-body{
    padding: 0 !important;
}

@media (min-width: 576px) {
    #contentNavigatorModal .modal-dialog{
        max-width: 360px;
    }
}

.content-navigator-modal-wrapper {
    border-radius: 12px;
    overflow: hidden;
    background-color: #ffffff;
}

.content-navigator-modal-wrapper .content-navigator-modal-image-wrapper {
    width: 100%;
    min-height: 292px;
    background-color: #155EEF;
    background-image: url('/theme/altibbi/images/content-navigator/modal_iphone.webp?v=1');
    background-repeat: no-repeat;
    background-position: center bottom;
    background-size: 100% auto;
    position: relative;
}

.content-navigator-modal-wrapper .content-navigator-modal-image-wrapper button{
    position: absolute;
    top: 12px;
    left: 12px;
    padding: 8px;
    opacity: .20;
}

.content-navigator-modal-wrapper .content-navigator-modal-content-wrapper {
    padding: 20px 16px 16px;
}

.content-navigator-modal-wrapper .content-navigator-modal-sub-title{
    color: #101828;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 18px;
    line-height: 22px;
    font-weight: 700;
    margin-bottom: 6px;
}

.content-navigator-modal-wrapper .content-navigator-modal-main-title{
    color: #101828;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 26px;
    line-height: 31px;
    font-weight: 700;
    margin-bottom: 6px;
}

.content-navigator-modal-wrapper .content-navigator-modal-note{
    color: #344054;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 14px;
    line-height: 20px;
    font-weight: 700;
    margin-bottom: 24px;
}

.content-navigator-modal-wrapper a{
    color: #ffffff;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 14px;
    line-height: 20px;
    font-weight: 700;
    background-color: #155EEF;
    border-radius: 8px;
    padding: 12px 18px;

    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    gap: 6px;
}

.content-navigator-modal-wrapper a:hover{
    background-color: #00bcaa;
}
           </style>
           <style>
            #contentNavigatorDownloadModal .modal-dialog-custom {
        max-width: 345px;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: calc(100vh - 1rem);
    }

    #contentNavigatorDownloadModal .btn-close-custom {
        top: 7px;
        left: 5px;
        z-index: 1051;
        font-size: 30px;
        color: #98A2B3;
        border: none;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    #contentNavigatorDownloadModal .modal-image {
        width: 345px;
        height: 431px;
        cursor: pointer;
        border-radius: 12px;
        display: block;
        max-width: 100%;
    }

    @media (max-width: 768px) {
        #contentNavigatorDownloadModal .modal-dialog-custom {
            margin: unset;
            max-width: 100%;
        }

        #contentNavigatorDownloadModal .btn-close-custom {
            top: 12px;
            left: 12px;
            width: 28px;
            height: 28px;
            font-size: 16px;
        }
    }
           </style>
           <script>
            var s2options_e9bc2761 = {"themeCss":".select2-container--krajee-bs4","sizeCss":"","doReset":true,"doToggle":false,"doOrder":false};
window.select2_69d74bc2 = {"allowClear":true,"theme":"krajee-bs4","width":"auto","placeholder":"التصنيفات","language":"ar"};

var CHAT_WIDGET_MESSAGE_ONE = "مرحبا بك في الطبي";
var CHAT_WIDGET_MESSAGE_TWO = "هل لديك استفسار عن";
var CHAT_WIDGET_MESSAGE_THREE = "المواضيع الطبية؟";
var LATER = "ذكرني لاحقاً";
var CALL_DR = "تحدث مع طبيب ";
var MEDICAL_QUESTION = "لديك استفسار طبي؟";
var CONTACT_US_NOW = "contact_us_now";
var OUR_DRS_HERE = "our_drs_here";
var HOW_CAN_I_HELP = "أطباؤنا هنا لمساعدتك";
           </script>
           <link href="https://altibbi.com/rss/editorial" rel="alternate" title="مقالات الطبي" type="application/rss+xml"/>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Medium.woff2" rel="preload" type="font/ttf"/>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Regular.woff2" rel="preload" type="font/ttf"/>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Bold.woff2" rel="preload" type="font/ttf"/>
           <link href="/favicon.ico" rel="icon" sizes="any"/>
           <link href="/favicon.svg" rel="icon" type="image/svg+xml"/>
           <link href="/favicon-48x48.png" rel="icon" sizes="48x48" type="image/png"/>
           <link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
           <link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
           <link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
           <link href="/manifest.json" rel="manifest"/>
           <link href="//cdn.altibbi.com" rel="dns-prefetch"/>
          </meta>
         </meta>
        </meta>
       </meta>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body data-country="EG">
  <script>
   let CURRENT_COUNTRY_ISO_CODE = "EG";
    let COUNTRY_ID = "214";
    let MEMBER_ID = null;
    let MEMBER_SUBSCRIBED = 0;
    let ENABLE_RASA_CHAT = 0;
    let ENABLE_ALTIBBI_CHAT = 1;
    let ENABLE_ALTIBBI_GSM = 1;
    let DYNAMIC_CTAS_LINKS = {"widget_script":"(function () {\r\n  \"use strict\";\r\n\r\n  var EVENT_NAME = \"main_wa_click\";\r\n  var CLEVERTAP_EVENT_NAME = \"whatsapp_widget_clicked\";\r\n  var GCLID_KEY = \"ab_gclid\";\r\n  var UTM_SOURCE_KEY = \"ab_utm_source\";\r\n  var UTM_CAMPAIGN_KEY = \"ab_utm_campaign\";\r\n  var ATTRIBUTION_TTL_DAYS = 90;\r\n\r\n  function onReady(fn) {\r\n    if (document.readyState === \"loading\") {\r\n      document.addEventListener(\"DOMContentLoaded\", fn);\r\n    } else {\r\n      fn();\r\n    }\r\n  }\r\n\r\n  function isMobileUA() {\r\n    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(\r\n      navigator.userAgent\r\n    );\r\n  }\r\n\r\n  function safeLocalGet(key) {\r\n    try {\r\n      return localStorage.getItem(key);\r\n    } catch (e) {\r\n      return null;\r\n    }\r\n  }\r\n\r\n  function safeLocalSet(key, value) {\r\n    try {\r\n      localStorage.setItem(key, value);\r\n    } catch (e) {}\r\n  }\r\n\r\n  function safeLocalRemove(key) {\r\n    try {\r\n      localStorage.removeItem(key);\r\n    } catch (e) {}\r\n  }\r\n\r\n  function setWithTTL(key, value, ttlDays) {\r\n    safeLocalSet(\r\n      key,\r\n      JSON.stringify({\r\n        v: value,\r\n        e: Date.now() + ttlDays * 864e5\r\n      })\r\n    );\r\n  }\r\n\r\n  function getWithTTL(key) {\r\n    var raw = safeLocalGet(key);\r\n\r\n    if (!raw) return null;\r\n\r\n    try {\r\n      var rec = JSON.parse(raw);\r\n\r\n      if (!rec || typeof rec.e !== \"number\" || Date.now() > rec.e) {\r\n        safeLocalRemove(key);\r\n        return null;\r\n      }\r\n\r\n      return rec.v;\r\n    } catch (e) {\r\n      safeLocalRemove(key);\r\n      return null;\r\n    }\r\n  }\r\n\r\n  function pushEvent(payload) {\r\n    window.dataLayer = window.dataLayer || [];\r\n    window.dataLayer.push(payload);\r\n  }\r\n\r\n  function pushCleverTap(eventName, props) {\r\n    try {\r\n      if (\r\n        window.clevertap &&\r\n        clevertap.event &&\r\n        typeof clevertap.event.push === \"function\"\r\n      ) {\r\n        clevertap.event.push(eventName, props || {});\r\n      }\r\n    } catch (e) {}\r\n  }\r\n\r\n  onReady(function init() {\r\n    // Unique guard so this does not get blocked by another Altibbi widget\r\n    if (document.querySelector(\".ab-custom-wa-button\")) return;\r\n\r\n    var IS_MOBILE = isMobileUA();\r\n\r\n    var params = new URLSearchParams(window.location.search);\r\n\r\n    var gclidFromUrl = params.get(\"gclid\");\r\n    var utmSourceFromUrl = params.get(\"utm_source\");\r\n    var utmCampaignFromUrl = params.get(\"utm_campaign\");\r\n\r\n    if (gclidFromUrl) setWithTTL(GCLID_KEY, gclidFromUrl, ATTRIBUTION_TTL_DAYS);\r\n    if (utmSourceFromUrl) setWithTTL(UTM_SOURCE_KEY, utmSourceFromUrl, ATTRIBUTION_TTL_DAYS);\r\n    if (utmCampaignFromUrl) setWithTTL(UTM_CAMPAIGN_KEY, utmCampaignFromUrl, ATTRIBUTION_TTL_DAYS);\r\n\r\n    var gclid = gclidFromUrl || getWithTTL(GCLID_KEY) || null;\r\n    var utm_source = utmSourceFromUrl || getWithTTL(UTM_SOURCE_KEY) || null;\r\n    var utm_campaign = utmCampaignFromUrl || getWithTTL(UTM_CAMPAIGN_KEY) || null;\r\n\r\n    // Same single link on mobile and desktop, per your button spec.\r\n    var link = \"https://go.altibbi.com/egypt\";\r\n    var chatChannel = \"egypt\"; // destination label; drop it if you don't need it (device_type already covers device)\r\n    var pageType = document.body.getAttribute(\"data-page-type\") || window.location.pathname;\r\n\r\n    var style = document.createElement(\"style\");\r\n\r\n    style.textContent = `\r\n      .ab-custom-wa-button {\r\n        position: fixed;\r\n        bottom: 24px;\r\n        right: 25px;\r\n        z-index: 100;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta {\r\n        width: 250px !important;\r\n        height: 55px;\r\n        background-color: #25d366;\r\n        border-radius: 28px;\r\n        min-width: 50px;\r\n        box-shadow: 0 6px 18px rgb(0 0 0 / .20);\r\n        display: flex;\r\n        align-items: center;\r\n        justify-content: center;\r\n        color: #fff !important;\r\n        text-decoration: none;\r\n        transition: background-color .2s ease;\r\n        border: none;\r\n        font-size: 18px;\r\n        font-weight: 700;\r\n        line-height: 1;\r\n        -webkit-font-smoothing: antialiased;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta:hover {\r\n        background-color: #20b959;\r\n        color: #fff !important;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta:focus-visible {\r\n        outline: 2px solid #fff;\r\n        outline-offset: 2px;\r\n      }\r\n\r\n      @media (max-width: 767px) {\r\n        .ab-custom-wa-button {\r\n          right: 15px;\r\n          bottom: 24px;\r\n        }\r\n\r\n        .ab-custom-wa-button .whats-cta {\r\n          width: 230px !important;\r\n          height: 54px;\r\n          font-size: 17px;\r\n        }\r\n      }\r\n    `;\r\n\r\n    document.head.appendChild(style);\r\n\r\n    var widget = document.createElement(\"div\");\r\n\r\n    widget.className = \"ab-custom-wa-button\";\r\n    widget.setAttribute(\"dir\", \"rtl\");\r\n\r\n    widget.innerHTML = `\r\n      <a href=\"${link}\"\r\n         class=\"whats-cta ab-custom-wa-link\"\r\n         target=\"_blank\"\r\n         rel=\"nofollow noopener\"\r\n         data-chat-channel=\"${chatChannel}\"\r\n         data-chat-placement=\"button\"\r\n         data-chat-link=\"${link}\">\r\n        <span>تحدث مع طبيب</span>\r\n      </a>\r\n    `;\r\n\r\n    document.body.appendChild(widget);\r\n\r\n    document.addEventListener(\r\n      \"click\",\r\n      function (e) {\r\n        var linkEl = e.target.closest(\".ab-custom-wa-link\");\r\n\r\n        if (!linkEl) return;\r\n\r\n        var props = {\r\n          chat_channel: linkEl.dataset.chatChannel,\r\n          chat_placement: linkEl.dataset.chatPlacement,\r\n          chat_link: linkEl.dataset.chatLink || linkEl.href,\r\n          device_type: IS_MOBILE ? \"mobile\" : \"desktop\",\r\n          page_path: location.pathname,\r\n          page_type: pageType,\r\n          utm_source: utm_source,\r\n          utm_campaign: utm_campaign,\r\n          gclid: gclid\r\n        };\r\n\r\n        pushEvent(Object.assign({ event: EVENT_NAME }, props));\r\n        pushCleverTap(CLEVERTAP_EVENT_NAME, props);\r\n      },\r\n      true\r\n    );\r\n  });\r\n})();\r\n","subscribe_ribbon_title":"","subscribe_ribbon_body":"","subscribe_ribbon_link":"","mobile":{"sticky_repo_link":"https://go.altibbi.com/egypt","inread_link":"https://go.altibbi.com/egypt","inread_answer_link":"https://go.altibbi.com/egypt","inread_qa_link":"https://go.altibbi.com/egypt","inread_article_ribbon_link":"https://go.altibbi.com/egypt","inread_term_ribbon_link":"https://go.altibbi.com/egypt","navbar_cta":"https://go.altibbi.com/egypt","lab_test_cta":"https://go.altibbi.com/egypt","preg_header_cta":"https://go.altibbi.com/egypt","riaya_link":"https://go.altibbi.com/egypt","homepage_cta":"https://go.altibbi.com/egypt","quiz_cta_link":"https://go.altibbi.com/egypt","drug_inread_link":"https://go.altibbi.com/egypt","q_and_a_banner":"https://go.altibbi.com/egypt","header_call_cta":"https://go.altibbi.com/egypt","header_chat_cta":"https://go.altibbi.com/egypt","mental_health_wa_link":"https://go.altibbi.com/egypt","nav_cta_link":"https://go.altibbi.com/egypt"},"desktop":{"sticky_repo_link":"https://go.altibbi.com/egypt","inread_link":"https://go.altibbi.com/egypt","inread_answer_link":"https://go.altibbi.com/egypt","inread_qa_link":"https://go.altibbi.com/egypt","inread_article_ribbon_link":"https://go.altibbi.com/egypt","inread_term_ribbon_link":"https://go.altibbi.com/egypt","navbar_cta":"https://go.altibbi.com/egypt","lab_test_cta":"https://go.altibbi.com/egypt","preg_header_cta":"https://go.altibbi.com/egypt","riaya_link":"https://go.altibbi.com/egypt","homepage_cta":"https://go.altibbi.com/egypt","quiz_cta_link":"https://go.altibbi.com/egypt","drug_inread_link":"https://go.altibbi.com/egypt","q_and_a_banner":"https://go.altibbi.com/egypt","header_call_cta":"https://go.altibbi.com/egypt","header_chat_cta":"https://go.altibbi.com/egypt","mental_health_wa_link":"https://go.altibbi.com/egypt","nav_cta_link":"https://go.altibbi.com/egypt"}};
    let ENABLE_NAVIGATOR_STICKY = 0;
    let ENABLE_CONTENT_NAVIGATOR = 1;
    let IS_CLARITY_ENABLE = 0;
  </script>
  <!-- AdBlockers Detector  -->
  <div id="ad-blocker-detector">
   <div class="adBanner">
   </div>
  </div>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WHXVK4VT" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <!--header-->
  <header class="sticky-top bg-white" id="header">
   <nav class="new-navbar navbar navbar-expand-xl navbar-light bg-white position-relative py-2 py-xl-3 border-bottom border-gray-6">
    <div class="container d-flex align-items-center justify-content-between mb-0">
     <div class="d-flex align-items-center">
      <button aria-controls="navMain" aria-expanded="false" aria-label="فتح القائمة" class="navbar-toggler new-burger border-0 p-2 d-xl-none collapsed" data-event-name="Menu Opened" data-target="#navMain" data-toggle="collapse" type="button">
       <img alt="burger menu icon" class="burger-open" height="24" src="/theme/altibbi/icons/tbi-burger-menu.svg" width="24"/>

In [7]:
from bs4 import BeautifulSoup

soup_categories = BeautifulSoup(response.text, 'html.parser')

select_element_all = soup_categories.find('select', {'id': 'w1'})

all_categories = []
if select_element_all:
    options_all = select_element_all.find_all('option')
    all_categories = [(option.get_text(strip=True), option['value']) for option in options_all if option.get('value')]
    print("Name of Categorys : ")
    for cat_name, cat_value in all_categories:
        print(f" Category: {cat_value}")
else:
    print("end of category")

Name of Categorys :
 Category: امراض-الغدد-الصماء
 Category: مرض-السكري
 Category: امراض-الجهاز-التنفسي
 Category: امراض-الدم
 Category: ارتفاع-ضغط-الدم
 Category: جراحة-العظام
 Category: جراحة-عامة
 Category: الاورام-الخبيثة-والحميدة
 Category: الامراض-الجلدية
 Category: الامراض-الجنسية
 Category: العقم
 Category: ارجية-حساسية
 Category: امراض-الاطفال
 Category: امراض-نفسية
 Category: الامراض-العصبية
 Category: انف-اذن-وحنجرة
 Category: الحمل-والولادة
 Category: امراض-المسالك-البولية-والتناسلية
 Category: امراض-العيون
 Category: جراحة-نسائية
 Category: الطب-البديل
 Category: الطب-الوقائي
 Category: علم-الاحياء
 Category: مختبر
 Category: علم-المناعة
 Category: مطاعيم-و-لقاحات
 Category: كيمياء-حيوية
 Category: كيمياء
 Category: علم-الاشعة
 Category: علم-النفس
 Category: علم-الاجنة
 Category: تغذية
 Category: فيزياء
 Category: تاريخ-الطب
 Category: علم-الصيدلة
 Category: ادوية
 Category: اسعاف-اولي
 Category: صحة-المراة
 Category: صحة-الرجل
 Category: صحة-الاسنان
 Category: صحة-المسنين
 Category: الصحة-الجنسية
 Category: البشرة-والجمال
 Category: الصحة-النفسية
 Category: اعشاب-طبية
 Category: الامراض-الوراثية
 Category: امراض-العضلات-والعظام-و-المفاصل
 Category: جراحة-تجميل
 Category: الامراض-المعدية
 Category: فيزيولوجيا
 Category: امراض-القلب-و-الشرايين
 Category: الطب-العام
 Category: الامراض-الرثويه
 Category: علم-الاحياء-الدقيقة
 Category: علم-الوراثة
 Category: امراض-الجهاز-الهضمي
 Category: صحة-الطفل
 Category: امراض-الاسنان
 Category: امراض-باطنية
 Category: علم-التشريح
 Category: فيتامينات-و-معادن
 Category: هرمونات
 Category: علم-السموم
 Category: صحة-عامة
 Category: جراحة-الاعصاب
 Category: جراحة-القلب-والشرايين
 Category: تشخيص
 Category: تخدير
 Category: ادمان
 Category: علاج-طبيعي
 Category: امراض-نسائية
 Category: علم-الامراض
 Category: علم-الانسجة
 Category: علم-النبات
 Category: تجهيزات-طبية
 Category: امراض-الاستقلاب
 Category: تشوهات-خلقية
 Category: كيمياء-عضوية
 Category: امراض-الفم
 Category: جراحة-المسالك-البولية
 Category: جراحة-الفك-والاسنان
 Category: اخبار-الطبي
 Category: الصحة-و-الرياضة
 Category: رمضان
 Category: خدمات-طبية
 Category: بصريات
 Category: علم-البيئة
 Category: طب-الاسنان
 Category: حمل-الانابيب
 Category: جراحة-الاوعية-الدموية
 Category: جراحة-الاطفال

In [8]:
print(len(all_categories))

91

In [9]:
books=soup.find_all(class_='question-item-container')

In [10]:
books[0]

<div class="question-item-container">
<div class="d-flex justify-content-between align-items-center flex-wrap">
<div class="age">
<span class="font-regular">سؤال من </span>
            أنثى 20 سنة        </div>
<a class="category-info d-block" href="/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A">أمراض الجهاز التنفسي</a>
</div>
<div itemprop="mainEntity" itemscope="" itemtype="https://schema.org/Question">
<a class="question-text mt-17 id-5-5" href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A/%D9%83%D8%A7%D9%86-%D8%B9%D9%86%D8%AF%D9%8A-%D8%A8%D8%B1%D8%AF-%D9%85%D9%86-%D8%A7%D8%B3%D8%A8%D9%88%D8%B9%D9%8A%D9%86-%D9%85%D8%AB%D9%84%D8%A7-%D9%83%D8%A7%D9%86-%D8%A7%D9%84%D8%A7%D9%88%D9%84-%D9%81%D9%8A-%D9%88%D8%AC%D8%B9-%D9%88%D8%A7%D8%AD%D8%AA%D9%82%D8%A7%D9%86-1853064">
<h2 class="question-text mt-17 id-5-5" itemprop="name">
                كان عندي برد من اسبوعين مثلا كان الاول في وجع واحتقان في الزور و انسداد انف وطبعا رشخ بعد اسبوعين لسه قي رشح جامد وانسداد انف والمخاط تقيل ولونه اخضر...            </h2>
</a>
<!-- SEO -->
<div class="hide" itemprop="acceptedAnswer" itemscope="" itemtype="https://schema.org/Answer">
<div itemprop="text">
<p>سلامتك، أتمنى أن تشعر بتحسن قريباً. من المؤلم أن تستمر أعراض البرد لفترة طويلة، ما تصفه من استمرار الرشح، انسداد الأنف، والمخاط الكثيف ذي اللون الأخضر بعد أسبوعين من بداية أعراض البرد قد يشير إلى عدة احتمالات، وغالباً ما يكون الجسم لا يزال في طور التعافي أو قد يكون هناك تطور:</p>
<p><strong>الاحتمالات الشائعة:</strong></p>
<ul>
<li><strong>التهاب الجيوب الأنفية الفيروسي الممتد:</strong> في بعض الأحيان، يمكن أن تستمر أعراض البرد الفيروسي لفترة أطول من المعتاد، وقد تتغير طبيعة المخاط مع استمرار الالتهاب.</li>
<li><strong>التهاب الجيوب الأنفية البكتيري الثانوي:</strong> بعد عدوى فيروسية، قد تصاب الجيوب الأنفية بعدوى بكتيرية. هذا غالباً ما يتسبب في زيادة كثافة المخاط وتغير لونه إلى الأخضر أو الأصفر، وقد يصاحبه ألم في الوجه أو صداع.</li>
<li><strong>حساسية الأنف:</strong> قد تكون الأعراض مستمرة بسبب الحساسية الموسمية أو الدائمة، والتي يمكن أن تتفاقم مع أي تهيج بسيط في الجهاز التنفسي.</li>
<li><strong>استمرار التهاب الأنف الفيروسي:</strong> بعض الفيروسات المسببة لنزلات البرد قد تستمر أعراضها لفترة أطول، خاصة مع تغير العوامل البيئية.</li>
</ul>
<p><strong>الأدوية التي استخدمتها:</strong></p>
<p>الأدوية التي ذكرتها (ديكاسنت، اتروفين، بخاخ كورتيزون، محلول ملح) تهدف إلى تخفيف الاحتقان والالتهاب. استخدام بخاخات الكورتيزون والمحلول الملحي مفيد بشكل عام في حالات التهاب الأنف والجيوب الأنفية، ولكن فعاليتها تعتمد على سبب المشكلة ومدى شدتها.</p>
<p><strong>خطوات قد تساعد:</strong></p>
<ul>
<li><strong>الاستمرار في استخدام محلول الملح:</strong> يساعد على ترطيب الأغشية المخاطية وتخفيف كثافة المخاط.</li>
<li><strong>الاستنشاق بالبخار:</strong> يمكن أن يساعد بخار الماء الدافئ (بدون إضافة زيوت عطرية قوية) في فتح الممرات الأنفية وتخفيف الاحتقان.</li>
<li><strong>شرب السوائل الدافئة:</strong> يساعد في ترطيب الجسم وتخفيف لزوجة المخاط.</li>
<li><strong>الراحة الكافية:</strong> ضرورية لتمكين الجسم من التعافي.</li>
<li><strong>تجنب المهيجات:</strong> مثل الدخان، الروائح القوية، والغبار.</li>
</ul>
<p>من الأفضل مراجعة الطبيب المختص للتأكد والاطمئنان، خاصة إذا استمرت الأعراض أو ساءت.</p> </div>
</div>
</div>
<div class="question-tags-container-listing">
</div>
<div class="div-line"></div>
<div class="doctor-answer-fqaa justify-content-start align-items-lg-end d-flex align-items-sm-center">
<div class="d-flex justify-content-start align-items-start">
<div class="doctor-image-fqaa ml-auto">
<a href="https://altibbi.com/الدليل-الطبي/%D8%B3%D9%8A%D9%86%D8%A7-%D9%85%D9%86-%D8%A7%D9%84%D8%B7%D8%A8%D9%8A-227758">
<img alt="سينا من الطبي" height="45" loading="lazy" src="/theme/altibbi/images/question/logo.webp" width="45"/>
</a>
</div>
<div class="doctor-details-fqaa mr-3">
<p class="answer-fqaa mb-lg-1">أجاب عن السؤال</p>
<a class="d-block dr-name-fqaa" href="https://altibbi.com/الدليل-الطبي/%D8%B3%D9%8A%D9%86%D8%A7-%D9%85%D9%86-%D8%A7%D9%84%D8%B7%D8%A8%D9%8A-227758">
                    د. سينا من الطبي                </a>
<time class="date-added-fqaa display-mobile">
<img alt="date-icon" height="9" loading="lazy" src="/theme/altibbi/images/widgets/clock.svg" width="9"/>
                    4 أكتوبر 2026                </time>
</div>
</div>
<time class="date-added-fqaa hide-mobile">
<img alt="date-icon" height="14" loading="lazy" src="/theme/altibbi/images/widgets/clock.svg" width="14"/>
            4 أكتوبر 2026        </time>
<a class="d-block see-answer-button-fqaa mr-auto" href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A/%D9%83%D8%A7%D9%86-%D8%B9%D9%86%D8%AF%D9%8A-%D8%A8%D8%B1%D8%AF-%D9%85%D9%86-%D8%A7%D8%B3%D8%A8%D9%88%D8%B9%D9%8A%D9%86-%D9%85%D8%AB%D9%84%D8%A7-%D9%83%D8%A7%D9%86-%D8%A7%D9%84%D8%A7%D9%88%D9%84-%D9%81%D9%8A-%D9%88%D8%AC%D8%B9-%D9%88%D8%A7%D8%AD%D8%AA%D9%82%D8%A7%D9%86-1853064">
            اجابة الطبيب            <img alt="arrow" class="mr-1 display-mobile-inline" height="13" loading="lazy" src="/theme/altibbi/icons/tbi-arrow-left-thin.svg" width="7">
</img></a>
</div>
</div>

In [11]:
category=[]
question=[]
answer=[]
for book in books:
  category.append(book.a.text)
  question.append(book.find(class_='question-text mt-17 id-5-5').text)
  answer.append(book.find(class_='hide').text)

In [12]:
len(question)

7

In [13]:
books[0].find(class_='question-text mt-17 id-5-5').text

'\n\n                كان عندي برد من اسبوعين مثلا كان الاول في وجع واحتقان في الزور و انسداد انف وطبعا رشخ بعد اسبوعين لسه قي رشح جامد وانسداد انف والمخاط تقيل ولونه اخضر...            \n'

In [14]:
books[0].find(class_='hide').text

'\n\nسلامتك، أتمنى أن تشعر بتحسن قريباً. من المؤلم أن تستمر أعراض البرد لفترة طويلة، ما تصفه من استمرار الرشح، انسداد الأنف، والمخاط الكثيف ذي اللون الأخضر بعد أسبوعين من بداية أعراض البرد قد يشير إلى عدة احتمالات، وغالباً ما يكون الجسم لا يزال في طور التعافي أو قد يكون هناك تطور:\nالاحتمالات الشائعة:\n\nالتهاب الجيوب الأنفية الفيروسي الممتد: في بعض الأحيان، يمكن أن تستمر أعراض البرد الفيروسي لفترة أطول من المعتاد، وقد تتغير طبيعة المخاط مع استمرار الالتهاب.\nالتهاب الجيوب الأنفية البكتيري الثانوي: بعد عدوى فيروسية، قد تصاب الجيوب الأنفية بعدوى بكتيرية. هذا غالباً ما يتسبب في زيادة كثافة المخاط وتغير لونه إلى الأخضر أو الأصفر، وقد يصاحبه ألم في الوجه أو صداع.\nحساسية الأنف: قد تكون الأعراض مستمرة بسبب الحساسية الموسمية أو الدائمة، والتي يمكن أن تتفاقم مع أي تهيج بسيط في الجهاز التنفسي.\nاستمرار التهاب الأنف الفيروسي: بعض الفيروسات المسببة لنزلات البرد قد تستمر أعراضها لفترة أطول، خاصة مع تغير العوامل البيئية.\n\nالأدوية التي استخدمتها:\nالأدوية التي ذكرتها (ديكاسنت، اتروفين، بخاخ كورتيزون، محلول ملح) تهدف إلى تخفيف الاحتقان والالتهاب. استخدام بخاخات الكورتيزون والمحلول الملحي مفيد بشكل عام في حالات التهاب الأنف والجيوب الأنفية، ولكن فعاليتها تعتمد على سبب المشكلة ومدى شدتها.\nخطوات قد تساعد:\n\nالاستمرار في استخدام محلول الملح: يساعد على ترطيب الأغشية المخاطية وتخفيف كثافة المخاط.\nالاستنشاق بالبخار: يمكن أن يساعد بخار الماء الدافئ (بدون إضافة زيوت عطرية قوية) في فتح الممرات الأنفية وتخفيف الاحتقان.\nشرب السوائل الدافئة: يساعد في ترطيب الجسم وتخفيف لزوجة المخاط.\nالراحة الكافية: ضرورية لتمكين الجسم من التعافي.\nتجنب المهيجات: مثل الدخان، الروائح القوية، والغبار.\n\nمن الأفضل مراجعة الطبيب المختص للتأكد والاطمئنان، خاصة إذا استمرت الأعراض أو ساءت. \n'

In [16]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import time

data = []

all_categories = [
    ("امراض الجهاز التنفسي", "امراض-الجهاز-التنفسي")
]

for category_name, category_slug in all_categories:

    print(f"Scraping {category_name}")

    page = 1
    collected = 0

    while collected < 1000:

        url = f"https://altibbi.com/اسئلة-طبية/{category_slug}?page={page}"

        response = requests.get(url)
        soup = BeautifulSoup(response.text, "html.parser")

        questions = soup.find_all(class_="question-item-container")

        if not questions:
            break

        for q in questions:

            if collected >= 1000:
                break

            question = q.find(class_="question-text mt-17 id-5-5")
            answer = q.find(class_="hide")

            data.append([
                category_name,
                question.get_text(separator=" ") if question else "",
                answer.get_text(separator=" ") if answer else ""
            ])

            collected += 1

        page += 1
        time.sleep(1)

    print(f"Collected {collected} questions")

Scraping امراض الجهاز التنفسي
Collected 1000 questions

In [17]:
data_df = pd.DataFrame(data, columns=['category', 'question', 'answer'])
data_df.to_csv('data.csv', index=False)
print(len(data))
data_df.head()

1000

,category,question,answer
0,امراض الجهاز التنفسي,\n \n كان عندي برد من اسبوعين م...,\n \n سلامتك، أتمنى أن تشعر بتحسن قريباً. من ا...
1,امراض الجهاز التنفسي,\n \n انا بعانى من مشكلة عندى ن...,\n \n هناك اسباب عديده للالم ال...
2,امراض الجهاز التنفسي,\n \n عندي مزرعة فطر محاري بلشت...,\n \n السعال المزمن الذي ينتهي ...
3,امراض الجهاز التنفسي,\n \n صعوبة في التنفس وسيلان في...,\n \n انسداد الأنف مع السيلان و...
4,امراض الجهاز التنفسي,\n \n احس بوخز في اعلا القفص ال...,\n \n الوخزة في أعلى الصدر قد ت...

In [1]:
import pandas as pd
df = pd.read_csv(r'data.csv')
df.head()

,category,question,answer
0,أمراض الغدد الصماء,\n \n تثدي وتعرق مفرط في كل الج...,\n \n مساء الخير\nمحتاجه تفاصيل...
1,أمراض الغدد الصماء,\n \n ما سبب عدم نزول الوزن لل...,\n \n زيادة الوزن ومقاومة النزو...
2,أمراض الغدد الصماء,\n \n أنا مريض غدة درقية وأستخد...,\n \n الف سلامه عليكي \nمن اعرا...
3,أمراض الغدد الصماء,\n \n سيدة بعمر ٥٢ سنه هل تحليل...,\n \n بحاجة تحليل بحاجةTRAb Ant...
4,أمراض الغدد الصماء,\n لدي تحليل غدة درقية ٣.٤٢ وT4 0.82 \r...,\n \n بناءً على ما ذكرت، إليك تفسير مبسط للنتا...

In [2]:
df["category"].value_counts()

category
أمراض الغدد الصماء      1000
مرض السكري              1000
أمراض الجهاز التنفسي    1000
أمراض الدم              1000
ارتفاع ضغط الدم         1000
                        ...
علم الأنسجة                5
أخبار الطبي                2
أدوية                      1
كيمياء عضوية               1
علم البيئة                 1
Name: count, Length: 91, dtype: int64

In [19]:
df["answer"][0]

'\n \n سلامتك، أتمنى أن تشعر بتحسن قريباً. من المؤلم أن تستمر أعراض البرد لفترة طويلة، ما تصفه من استمرار الرشح، انسداد الأنف، والمخاط الكثيف ذي اللون الأخضر بعد أسبوعين من بداية أعراض البرد قد يشير إلى عدة احتمالات، وغالباً ما يكون الجسم لا يزال في طور التعافي أو قد يكون هناك تطور: \n الاحتمالات الشائعة: \n \n التهاب الجيوب الأنفية الفيروسي الممتد:  في بعض الأحيان، يمكن أن تستمر أعراض البرد الفيروسي لفترة أطول من المعتاد، وقد تتغير طبيعة المخاط مع استمرار الالتهاب. \n التهاب الجيوب الأنفية البكتيري الثانوي:  بعد عدوى فيروسية، قد تصاب الجيوب الأنفية بعدوى بكتيرية. هذا غالباً ما يتسبب في زيادة كثافة المخاط وتغير لونه إلى الأخضر أو الأصفر، وقد يصاحبه ألم في الوجه أو صداع. \n حساسية الأنف:  قد تكون الأعراض مستمرة بسبب الحساسية الموسمية أو الدائمة، والتي يمكن أن تتفاقم مع أي تهيج بسيط في الجهاز التنفسي. \n استمرار التهاب الأنف الفيروسي:  بعض الفيروسات المسببة لنزلات البرد قد تستمر أعراضها لفترة أطول، خاصة مع تغير العوامل البيئية. \n \n الأدوية التي استخدمتها: \n الأدوية التي ذكرتها (ديكاسنت، اتروفين، بخاخ كورتيزون، محلول ملح) تهدف إلى تخفيف الاحتقان والالتهاب. استخدام بخاخات الكورتيزون والمحلول الملحي مفيد بشكل عام في حالات التهاب الأنف والجيوب الأنفية، ولكن فعاليتها تعتمد على سبب المشكلة ومدى شدتها. \n خطوات قد تساعد: \n \n الاستمرار في استخدام محلول الملح:  يساعد على ترطيب الأغشية المخاطية وتخفيف كثافة المخاط. \n الاستنشاق بالبخار:  يمكن أن يساعد بخار الماء الدافئ (بدون إضافة زيوت عطرية قوية) في فتح الممرات الأنفية وتخفيف الاحتقان. \n شرب السوائل الدافئة:  يساعد في ترطيب الجسم وتخفيف لزوجة المخاط. \n الراحة الكافية:  ضرورية لتمكين الجسم من التعافي. \n تجنب المهيجات:  مثل الدخان، الروائح القوية، والغبار. \n \n من الأفضل مراجعة الطبيب المختص للتأكد والاطمئنان، خاصة إذا استمرت الأعراض أو ساءت.   \n'

In [20]:
df["question"][0]

'\n \n                كان عندي برد من اسبوعين مثلا كان الاول في وجع واحتقان في الزور و انسداد انف وطبعا رشخ بعد اسبوعين لسه قي رشح جامد وانسداد انف والمخاط تقيل ولونه اخضر...             \n'

In [30]:
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup

session = requests.Session()

start_url = ("https://altibbi.com/%D8%A7%D8%B3%D8%A6%D9%84%D8%A9-%D8%B7%D8%A8%D9%8A%D8%A9/"
             "%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-"
             "%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A")

response = session.get(start_url, timeout=30)
soup_categories = BeautifulSoup(response.text, "html.parser")

In [31]:
select_element_all = soup_categories.find("select", {"id": "w1"})

all_categories = []
if select_element_all:
    options_all = select_element_all.find_all("option")
    all_categories = [
        (option.get_text(strip=True), option["value"])
        for option in options_all if option.get("value")
    ]
print("Number of categories:", len(all_categories))

Number of categories: 91

In [32]:
def get_full_question(q_tag):
    """لو السؤال مقصوص (بينتهي بـ ...) بنجيبه كامل من صفحة السؤال."""
    text = q_tag.get_text(separator=" ")

    if not text.strip().endswith("..."):
        return text                  

    try:
        r = session.get(q_tag["href"], timeout=30)
        body = BeautifulSoup(r.text, "html.parser").select_one("div.qv-question-body")
        if body:
            return body.get_text(separator=" ")
    except requests.RequestException:
        pass

    return text

In [34]:
data = []

for category_name, category_slug in all_categories:

    print(f"Scraping {category_name}")

    page = 1
    collected = 0

    while collected < 1000:

        url = f"https://altibbi.com/اسئلة-طبية/{category_slug}?page={page}"

        try:
            response = session.get(url, timeout=30)
        except requests.RequestException as e:
            print(f"  Request failed on page {page}: {e}")
            break

        soup = BeautifulSoup(response.text, "html.parser")
        questions = soup.find_all(class_="question-item-container")

        if not questions:
            break

        for q in questions:

            if collected >= 1000:
                break

            question = q.find(class_="question-text mt-17 id-5-5")
            answer = q.find(class_="hide")

            data.append([
                category_name,
                get_full_question(question) if question else "",
                answer.get_text(separator=" ") if answer else ""
                
            ])

            collected += 1

        page += 1
        
        data_df = pd.DataFrame(data, columns=["category", "question", "answer"])
        data_df.to_csv("data.csv", index=False, encoding="utf-8-sig")

        time.sleep(1)

    print(f"Collected {collected} questions")


data_df = pd.DataFrame(data, columns=["category", "question", "answer"])
data_df.to_csv("data.csv", index=False, encoding="utf-8-sig")

print(len(data_df))
data_df.head()

Scraping أمراض الغدد الصماء
Collected 1000 questions
Scraping مرض السكري
Collected 1000 questions
Scraping أمراض الجهاز التنفسي
Collected 1000 questions
Scraping أمراض الدم
Collected 1000 questions
Scraping ارتفاع ضغط الدم
Collected 1000 questions
Scraping جراحة العظام
Collected 1000 questions
Scraping جراحة عامة
Collected 1000 questions
Scraping الأورام الخبيثة والحميدة
Collected 1000 questions
Scraping الأمراض الجلدية
Collected 1000 questions
Scraping الأمراض الجنسية
Collected 1000 questions
Scraping العقم
Collected 412 questions
Scraping أرجية  حساسية
Collected 572 questions
Scraping أمراض الأطفال
Collected 1000 questions
Scraping أمراض نفسية
Collected 1000 questions
Scraping الأمراض العصبية
Collected 1000 questions
Scraping أنف، أذن وحنجرة
Collected 1000 questions
Scraping الحمل والولادة
Collected 1000 questions
Scraping أمراض المسالك البولية والتناسلية
Collected 1000 questions
Scraping امراض العيون
Collected 1000 questions
Scraping جراحة نسائية
Collected 260 questions
Scraping الطب البديل
Collected 393 questions
Scraping الطب الوقائي
Collected 35 questions
Scraping علم الأحياء
Collected 51 questions
Scraping مختبر
Collected 232 questions
Scraping علم المناعة
Collected 98 questions
Scraping مطاعيم و لقاحات
Collected 36 questions
Scraping كيمياء حيوية
Collected 13 questions
Scraping كيمياء
Collected 20 questions
Scraping علم الأشعة
Collected 87 questions
Scraping علم النفس
Collected 385 questions
Scraping علم الأجنة
Collected 69 questions
Scraping تغذية
Collected 1000 questions
Scraping فيزياء
Collected 12 questions
Scraping تاريخ الطب
Collected 18 questions
Scraping علم الصيدلة
Collected 1000 questions
Scraping أدوية
Collected 1 questions
Scraping إسعاف أولي
Collected 79 questions
Scraping صحة المرأة
Collected 1000 questions
Scraping صحة الرجل
Collected 1000 questions
Scraping صحة الأسنان
Collected 1000 questions
Scraping صحة المسنين
Collected 17 questions
Scraping الصحة الجنسية
Collected 1000 questions
Scraping البشرة والجمال
Collected 1000 questions
Scraping الصحة النفسية
Collected 1000 questions
Scraping أعشاب طبية
Collected 404 questions
Scraping الامراض الوراثية
Collected 199 questions
Scraping أمراض العضلات والعظام و المفاصل
Collected 1000 questions
Scraping جراحة تجميل
Collected 1000 questions
Scraping الامراض المعدية
Collected 424 questions
Scraping فيزيولوجيا
Collected 36 questions
Scraping أمراض القلب و الشرايين
Collected 1000 questions
Scraping الطب العام
Collected 1000 questions
Scraping الأمراض الرثويه
Collected 40 questions
Scraping علم الأحياء الدقيقة
Collected 48 questions
Scraping علم الوراثة
Collected 47 questions
Scraping أمراض الجهاز الهضمي
Collected 1000 questions
Scraping صحة الطفل
Collected 1000 questions
Scraping أمراض الأسنان
Collected 1000 questions
Scraping أمراض باطنية
Collected 1000 questions
Scraping علم التشريح
Collected 81 questions
Scraping فيتامينات و معادن
Collected 182 questions
Scraping هرمونات
Collected 251 questions
Scraping علم السموم
Collected 68 questions
Scraping صحة عامة
Collected 1000 questions
Scraping جراحة الأعصاب
Collected 595 questions
Scraping جراحة القلب والشرايين
Collected 576 questions
Scraping تشخيص
Collected 261 questions
Scraping تخدير
Collected 56 questions
Scraping إدمان
Collected 1000 questions
Scraping علاج طبيعي
Collected 432 questions
Scraping أمراض نسائية
Collected 1000 questions
Scraping علم الأمراض
Collected 58 questions
Scraping علم الأنسجة
Collected 5 questions
Scraping علم النبات
Collected 5 questions
Scraping تجهيزات طبية
Collected 8 questions
Scraping أمراض الاستقلاب
Collected 7 questions
Scraping تشوهات خلقية
Collected 22 questions
Scraping كيمياء عضوية
Collected 1 questions
Scraping أمراض الفم
Collected 1000 questions
Scraping جراحة المسالك البولية
Collected 412 questions
Scraping جراحة الفك والأسنان
Collected 686 questions
Scraping أخبار الطبي
Collected 2 questions
Scraping الصحة و الرياضة
Collected 1000 questions
Scraping رمضان
Collected 32 questions
Scraping خدمات طبية
Collected 77 questions
Scraping بصريات
Collected 82 questions
Scraping علم البيئة
Collected 1 questions
Scraping طب الأسنان
Collected 1000 questions
Scraping حمل الأنابيب
Collected 12 questions
Scraping جراحة الأوعية الدموية
Collected 13 questions
Scraping جراحة الأطفال
Collected 16 questions
46929

,category,question,answer
0,أمراض الغدد الصماء,\n \n تثدي وتعرق مفرط في كل الج...,\n \n مساء الخير\nمحتاجه تفاصيل...
1,أمراض الغدد الصماء,\n \n ما سبب عدم نزول الوزن لل...,\n \n زيادة الوزن ومقاومة النزو...
2,أمراض الغدد الصماء,\n \n أنا مريض غدة درقية وأستخد...,\n \n الف سلامه عليكي \nمن اعرا...
3,أمراض الغدد الصماء,\n \n سيدة بعمر ٥٢ سنه هل تحليل...,\n \n بحاجة تحليل بحاجةTRAb Ant...
4,أمراض الغدد الصماء,\n لدي تحليل غدة درقية ٣.٤٢ وT4 0.82 \r...,\n \n بناءً على ما ذكرت، إليك تفسير مبسط للنتا...

In [35]:
data_df["answer"][0]

'\n \n                مساء الخير\nمحتاجه تفاصيل اكتر اذا كنت حضرتك مريض ضغط او سكر ايه الادويه اللي ماشي عليها\nف اي فحوصات عملتها قريب \nوالاعراض دي ظهرت من امتي             \n'

In [36]:
data_df["question"][0]

'\n \n                تثدي وتعرق مفرط في كل الجسم خاصتا الوجه والبطن والظهر              \n'

In [39]:
data_df.shape

(46929, 3)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46929 entries, 0 to 46928
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  46929 non-null  object
 1   question  46929 non-null  object
 2   answer    46929 non-null  object
dtypes: object(3)
memory usage: 1.1+ MB